### ISSUE TITLE
lifetime stdout

### ISSUE THREAD

**Issue by hainm** [mojyt/cpptraj#16]
Dan,

I implemented `lifetime` (from cpptraj analysis) in `pytraj` now. It seems that the statistics will be printed to stdout

```python
In [14]: pdb = pt.load_pdb_rcsb("1l2y")

In [15]: dslist = pdb.search_hbonds()

In [22]: pt.common_actions.lifetime(dslist[1])
#Set       Nlifetimes      MaxLT      AvgLT  TotFrames SetName
         0          2          1     1.0000          2 d0
Out[22]: array([ 1.])

```

it seems that cpptraj's manual does not have info about dumping to dataset. 
```python
In [17]: pt.info("lifetime")
        [out <filename>] <dsetarg0> [ <dsetarg1> ... ]
        [window <windowsize> [name <setname>]] [averageonly]
        [cumulative] [delta] [cut <cutoff>] [greater | less] [rawcurve]
        [fuzz <fuzzcut>] [nosort]
  Calculate lifetimes for specified data set(s), i.e. time that data is
  either greater than or less than <cutoff> (default: > 0.5). If <windowsize>
  is given calculate lifetimes over windows of given size.
```

**Comment by hainm** [comment]
@mojyt 

since this is already 15 days, so do you have opinion about this? :D

**Comment by mojyt** [comment]
Sorry, sometimes these notifications fall off my radar - one of the reasons
I would like to move more (all?) dev to github. As we have discussed before
there are several actions/analysis in cpptraj which give results outside
the normal dataset framework (some are denoted in the feature request doc).
Maybe we should chat about this IRL - it may be that in certain cases it
would be better to create a new dataset to address this rather than use the
basic ones in a complex way.

On Saturday, July 25, 2015, Hai Nguyen <notifications@github.com> wrote:

> @mojyt <https://github.com/mojyt>
>
> since this is already 15 days, so do you have opinion about this? :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/16#issuecomment-124946653>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
> Sorry, sometimes these notifications fall off my radar - one of the reasons
I would like to move more (all?) dev to github.

yeah, open issue to discuss on github is much easier our google doc.

> Maybe we should chat about this IRL - it may be that in certain cases it
would be better to create a new dataset to address this rather than use the
basic ones in a complex way.

I agree. Let me make a list of things should be fixed/added first.
