### ISSUE TITLE
AddSet(DataSet*): how can I get this right?

### ISSUE THREAD

**Issue by hainm** [mojyt/cpptraj#9]
hi @mojyt,

I am playing with AddSet methods in DataSetList class in pytraj. I have three tests here and expected got size=1 for DataSetList after using AddSet(DataSet*) method (where `size` is the number DataSet in DataSetList). However, two first tests resulted size=0. I got lost here. Can you tell me about this? thanks

    def test_0(self):
        dset_traj = DataSet_Coords_TRJ()
        dslist = DataSetList()

        # wrapper of "AddSet(DataSet*)
        dslist.add_existing_set(dset_traj)
        print (dslist.size) # = 0, but I expected "=1"

    def test_1(self):
        dset_traj = DataSet_MatrixDbl()
        dslist = DataSetList()

        # wrapper of "AddSet(DataSet*)
        dslist.add_existing_set(dset_traj)
        print (dslist.size) # = 0, but I expected "=1"

    def test_2(self):
        dslist = DataSetList()
              
        # wrapper of "AddSet(DataType, name, default_name)"
        dslist.add_set("coords", "name", "funny_name")
        print (dslist[0])
        print (dslist.size) # = 1 (is what I expected)

(you can pull Amber master, recompile pytraj and go to tests folder to run `python ./test_DataSetList_add_set_question.py`

**Comment by hainm** [comment]
:D 
I just double-checked this code and found out that `dset_traj` above has empty name. So the alternative question is can I just dset_traj.name = 'some_cool_name'?  (I tried to grep `SetName` but it does not exist). May be I need to go around like `dslist.add_set("coords", "name", "funny_name")`? 

    int DataSetList::AddSet( DataSet* dsIn ) {
      if (dsIn == 0 || dsIn->Name().empty()) return 1;
      DataSet* ds = CheckForSet( dsIn->Name(), dsIn->Idx(), dsIn->Aspect(), dsIn->Member() );
      if (ds != 0) {
        mprintf("Warning: DataSet '%s' already present.\n", ds->PrintName().c_str());
        return 1;
      }
      DataList_.push_back( dsIn );
      return 0;
    }

PS: btw, this is only minor question.

Hai

**Comment by mojyt** [comment]
Hi,

Every data set should have at least a name, otherwise you wouldn't be able
to search for it. You can just call the SetupSet() routine from DataSet (or
set the name some other way). You can either do that or add the set
directly. The AddSet(DataSet*) routine is for cases where setup occurs
outside the DataSetList (like for reference structures or when data is
being read externally etc).

Does this answer your question OK? Let me know if not. I will probably need
to revisit the way data sets are set up in the future. I've been meaning to
encapsulate all identifying info into some sort of DataSet Metadata class...

-Dan

On Mon, Mar 30, 2015 at 6:00 AM, Hai Nguyen <notifications@github.com>
wrote:

> :D
> I just double-checked this code and found out that dset_traj above has
> empty name. So the alternative question is can I just dset_traj.name =
> 'some_cool_name'? (I tried to grep SetName but it does not exist). May be
> I need to go around like dslist.add_set("coords", "name", "funny_name")?
>
> int DataSetList::AddSet( DataSet* dsIn ) {
>   if (dsIn == 0 || dsIn->Name().empty()) return 1;
>   DataSet* ds = CheckForSet( dsIn->Name(), dsIn->Idx(), dsIn->Aspect(), dsIn->Member() );
>   if (ds != 0) {
>     mprintf("Warning: DataSet '%s' already present.\n", ds->PrintName().c_str());
>     return 1;
>   }
>   DataList_.push_back( dsIn );
>   return 0;
> }
>
> PS: btw, this is only minor question.
>
> Hai
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/9#issuecomment-87650392>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
I see. You want to organize DataSetList like a dictionary.  In pytraj, I can get the DataSet from DSL either by indexing DSL[0] or by data's legend DSL['data_legend_example'].

thanks. 
Hai

**Comment by mojyt** [comment]
On Mon, Mar 30, 2015 at 11:35 AM, Hai Nguyen <notifications@github.com>
wrote:

> I see. You want to organize DataSetList like a dictionary. In pytraj, I
> can get the DataSet from DSL either by indexing DSL[0] or by data's legend
> DSL['data_legend_example'].
>

It's more just to keep track of what has already been created and avoid
collisions. For example, this needs to fail:

distance D1 :1 :2 out dist.agr
distance D1 :3 :4 out dist.agr

Both data sets can't be named D1.

-Dan


> thanks.
> Hai
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/9#issuecomment-87765657>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
@hainm -- I don't know if this is necessarily something you want to pull into pytraj.  The data set stuff that Dan put in cpptraj is absolutely necessary in cpptraj, because it sets up the bookkeeping machinery that Dan needs for his analyses inside cpptraj.  It needed to be added because there was no alternative.

But Python has a numpy-based library designed *specifically* for this kind of thing: [pandas](http://pandas.pydata.org/).  It is far more feature-rich than cpptraj's data sets and data set lists (pandas has a community of 300+ contributors with over 11k commits... nothing Dan writes in a year or so as a small component of his much bigger project will compete with that ;).

Here is one of my recent workflows:

1. Use `multidihedral` in cpptraj to generate phi, psi, and chip data sets, dumping to a single file.
2. Use `pandas.read_table` on that data file to load the data into a `pandas.DataFrame`.
3. Run that data through `scikit-learn`, `matplotlib`, etc.

In this case, `pandas` behaves more like you expect it to than cpptraj's DataSet and DataSetList; and for people tied into the scipy stack using Python for analysis, `pandas.DataFrame` is probably a better data structure to use here.  I would love it if I could just import pytraj, run multidihedral from it, then get back a DataFrame with the columns representing the data sets that it generates.

**Comment by hainm** [comment]
@swails 

Hi. I played with DSL in cpptraj because pytraj need it to pull the data directly from cpptraj. To the best of my cpptraj knowledge, I need to use cpptraj's DSL to perform Analysis. 

For example this is how pytraj use Analysis_Clustering:

        dslist = DataSetList()
        dflist = DataFileList()

        dslist.add_set("coords", "my_clustering", "")
        traj = mdio.load("./data/tz2.nc", "./data/tz2.parm7")
        dslist[0].top = traj.top
        dslist[0].load(traj)
        # add some arbitrary frames
        dslist.add_frame(traj[5])
        dslist.add_frame(traj[3])
        command = """
        crdset my_clustering :2-10 clusters 3 epsilon 4.0 summary ./output/avg.summary.dat nofit
        """
        act = Analysis_Clustering()
        act(command, traj.top, dslist=dslist, dflist=dflist)
        dflist.write_all_datafiles()

The whole idea is to perform whatever actions/analysis/modifications with traj/frame and then dump them to some traj holders, like DataSet_Coords_CRD in cpptraj and then controlling the clustering process. I just don't want save the traj/frame into disk and reload by cpptraj (like via CpptrajState class).

One thing in my TOOD list is to perform clustering in GPU (might connect cpptraj with this https://github.com/serban/kmeans), so I need to know how to pass info to cpptraj (via DataSet stuff) and tell it to do the final outputting. 

Per pandas's `DataFrame`, I am thinking about it too. One of my initial thoughs was to follow mdtraj for Topology object stuff. I checked `ParmEd` and it has this function now so I think `pytraj` will use this. For other stuff, "Yes", I will be considering `pandas`. Thanks for your suggestion. :+1: 

Hai

**Comment by hainm** [comment]
so here is my will-be-workflow

Use `multidihedral` in `pytraj/cpptraj` to generate phi, psi, and chip data sets, dumping to a `DataSet` (ds0, ...)
Use `pandas` to read ds0 dataset **internally** (without saving to disk) to pandas.DataFrame (ds[:] will return a python array)
Run that data through `scikit-learn`, `matplotlib`, etc.

**Comment by hainm** [comment]
here is an example of `multidihedral` analysis

http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/multidihedral_analysis.ipynb
